### ISSUE TITLE
CrudService.class Filter Issue, Question

### ISSUE THREAD

**Issue by stiffler17** [adminfaces/admin-persistence#17]
##### Issue Overview

Hi!

I have a question about your CrudService class.
You have a function "Count by filter using configRestrictions to count".
You can see this in the code area below.

I have a class with a 1-to-1 relationship. Also down in the code area.
The building class works great with your CRUD service. It has a UUID as id.
But the area class is running on a mistake.

I'll try to explain.
You get the Id field from the class via the metamodel. 
This works for the building class. Because the ID is a simple variable.
As shown on the Metamodel Building picture, the ID of the class is located under the id.
If I debug Metamodel Area the ID is located under the idClassAttributes field and not under id.

Is your CrudService ready for Ids like these and Ids like embedded keys?

Thanks

##### Additional Information
```
public class Building{

    @Id
    private UUID uuid;
    private Area area;
    ...
}

public class Area{
    @Id
    @OneToOne
    private Building building;
    ...
    ...
 
}

```

```
    /**
     * Count by filter using configRestrictions to count
     *
     * @param filter
     * @return
     */
    public Long count(Filter<T> filter) {
        SingularAttribute<? super T, PK> id = entityManager.getMetamodel().entity(entityClass).getId(entityKey);
        return configRestrictions(filter)
                .select(Long.class, count(id))
                .getSingleResult();
    }
```

### Metamodel Building during debugging

![metamodel_building](https://user-images.githubusercontent.com/14252961/31726307-ddc6e250-b426-11e7-98dd-f269639c8b9d.png)

### Metamodel Area during debugging
![metamodel_area](https://user-images.githubusercontent.com/14252961/31726420-362a8a8c-b427-11e7-82f1-dff9c16d2601.png)

**Comment by stiffler17** [comment]
Big Sorry!

My Annotation was wrong.

Please delete this nonsense.

**Comment by rmpestano** [comment]
👍
