### ISSUE TITLE
Unresolved ambiguous dependency

### ISSUE THREAD

**Issue by vbini21** [adminfaces/admin-persistence#47]
Creation of a new menu.

Due to the creation of a new menu I have introduced a new class ReceptionListMB. That means CarListMB still exists for the Car menu. This has led to Unresolved ambiguous dependency when I inject CrudService<Car, Integer> carCrudService; and CrudService<Reception, Integer> receptionCrudService; .
 I have introduced qualifiers and placed them before the respective class names but the problem still persists.

ReceptionListMB code extract:

@Named
@ViewScoped
@BeanService(ReceptionService.class)
@ReceptionQ
public class ReceptionListMB extends CrudMB implements Serializable {

@Inject
ReceptionService receptionService;

@Inject
@Service
CrudService<Reception, Integer> receptionCrudService; //generic injection example

@Inject
public void initService() {
    setCrudService(receptionService);
}

CarListMB code extract:

@Named
@ViewScoped
@BeanService(CarService.class)
@CarQ
public class CarListMB extends CrudMB implements Serializable {

@Inject
CarService carService;

@Inject
@Service    
CrudService<Car, Integer> carCrudService; //generic injection example

@Inject
public void initService() {
    setCrudService(carService);
}
How can I resolve this problem?

**Comment by rmpestano** [comment]
Hi @vbini21, looking at the code you provided it looks good. 
There is an example of multiple generic injections working on the sample scaffold app here: https://github.com/adminfaces/generated-scaffold-app/blob/master/src/main/java/com/github/adminfaces/app/bean/AppLists.java

Can you compare with your app? or maybe you can provide a sample project which reproduces the issue?

Which app server and version are you using?

**Comment by vbini21** [comment]
I am using wildfly 16.0. The error appears in netbeans even as you code as a warning. NB am injecting in different classes not within the same class as you have guided me on the above link:

@Named
@ApplicationScoped
public class AppLists implements Serializable {

	@Inject
	@Service
	private CrudService<Room, Long> roomService;
	private Set<Room> rooms;

	@Inject
	@Service
	private CrudService<Speaker, Long> speakerService;
	private Set<Speaker> speakers;

	@Inject
	@Service
	private CrudService<Talk, Long> talkService;
	private Set<Talk> talks;

Sample project attached herewith.
[afiasoft_web.zip](https://github.com/adminfaces/admin-persistence/files/5611982/afiasoft_web.zip)

**Comment by rmpestano** [comment]
Thanks for the sample. 

On the sample code if I remove `@EJB` from:

```

    @Inject
    //@EJB
    @Service    
    private CrudService<Car, Integer> carCrudService; //generic injection example
```

Then the application starts without a problem

**Comment by vbini21** [comment]
Thanks for the response.
The application starts but have you tried clicking on the reception or the car menu and then click new Button.
There goes the error linked to the problem am facing.


Date/time: Nov 29, 2020 6:31:18 PM
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
User IP: 127.0.0.1
Request URI: http://localhost:8080/admin-starter/reception-list.xhtml
Ajax request: No
Exception type: javax.el.PropertyNotFoundException
Message: Target Unreachable, identifier 'ReceptionListMB' resolved to null

**Comment by vbini21** [comment]
I have installed the generated-scaffold-app.
It has what I needed to navigate through pages. Let me have a look at it first. Thank You

**Comment by rmpestano** [comment]
The error below is because you have `ReceptionListMB` instead of `receptionListMB` on reception-list page:
```
Exception type: javax.el.PropertyNotFoundException
Message: Target Unreachable, identifier 'ReceptionListMB' resolved to null
```

**Comment by vbini21** [comment]
True, i forgot to go by the rules. Thanks
